import { StyleSheet } from 'react-native';
import colors from '../colors/colors';

const theme = StyleSheet.create({
	container: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
	},
	image: {
		resizeMode: 'contain',
		width: 250,
		height: 250,
		alignSelf: 'center',
	},
	inputContainer: {
		width: '60%',
	},
	input: {
		borderWidth: 2,
		paddingHorizontal: 15,
		paddingVertical: 10,
		marginTop: 10,
		borderRadius: 10,
	},
	buttonContainer: {
		width: '100%',
		justifyContent: 'center',
		alignItems: 'center',
		marginTop: 40,
	},
	button: {
		padding: 10,
		borderRadius: 10,
		alignItems: 'center',
		alignSelf: 'center',
		marginTop: 30,
	},
	buttonText: {
		fontWeight: '500',
		fontSize: 16,
	},
	buttonTransparent: {
		width: 30,
		height: 30,
		alignItems: 'center',
	},
	buttonSettings: {
		alignSelf: 'flex-end',
		bottom: 340,
		right: 10,
	},
	bottomTab: {
		position: 'absolute',
		borderTopWidth: 0,
		bottom: 50,
		left: 20,
		right: 20,
		elevation: 5,
		borderRadius: 15,
		height: 70,
		paddingBottom: 0,
		shadowColor: '#000000',
		shadowOffset: {
			width: 0,
			height: 10,
		},
		shadowOpacity: 0.25,
		shadowRadius: 3.5,
	},
	bottomTabText: {
		fontWeight: '500',
		fontSize: 16,
		bottom: 5,
	},
	cardContainer: {
		height: 50,
		marginVertical: 30,
	},
	settingsContainer: {
		flex: 1,
		flexDirection: 'row',
		alignItems: 'center',
		alignContent: 'space-between',
		justifyContent: 'space-between',
		width: '90%',
		maxHeight: '5%',
		borderBottomWidth: 1,
	},
	settingsButton: {
		width: '100%',
	},
	modalContainer: {
		flex: 1,
		justifyContent: 'center',
		alignItems: 'center',
		marginTop: 22,
		margin: 20,
		borderRadius: 20,
		padding: 35,
		shadowColor: '#000',
		shadowOffset: {
			width: 0,
			height: 2,
		},
		shadowOpacity: 0.25,
		shadowRadius: 4,
		elevation: 5,
	},
	modalButton: {
		padding: 10,
		borderRadius: 10,
		alignItems: 'center',
		alignSelf: 'center',
		marginTop: 30,
		width: 75,
	},
	editContainer: {
		//flex: 1,
		//flexDirection: 'row',
		alignItems: 'center',
		alignContent: 'space-between',
		justifyContent: 'space-between',
		width: '90%',
		marginTop: 10,
		//maxHeight: '5%',
		borderBottomWidth: 1,
	},
	editButton: {
		padding: 5,
		borderRadius: 10,
		alignItems: 'center',
		width: 70,
		maxHeight: 50,
	},
	editInput: {
		borderWidth: 1,
		paddingHorizontal: 15,
		paddingVertical: 10,
		borderRadius: 10,
		width: 200,
		marginBottom: 10,
		marginTop: 10,
	},
	cartItemText: {
		fontWeight: '500',
	},
	cartItemContainer: {
		//flex: 1,
		//alignSelf: 'center',
		//justifyContent: 'center',
		//alignContent:'center',
		//alignItems: 'center',
		marginLeft: 10,
		marginTop: 20,
	},
	cartItemFooter: {
		marginTop: 'auto',
		flexDirection: 'row',
		alignItems: 'center',
	},
	cartTotalsContainer: {
		marginTop: 20,
		paddingTop: 10,
		borderColor: 'gainsboro',
		borderTopWidth: 1,
	},
	cartRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		marginVertical: 2,
	},
});

export default theme;
